apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "rollouts-demo.name" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- toYaml .Values.gateway.hosts | nindent 4 }}
